name: Sync to Hugging Face Space

on:
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
          
      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Destroy the local git history so Hugging Face doesn't see old massive files
          rm -rf .git
          git init
          git checkout -b main
          
          # Configure bot identity
          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"
          
          # Add current files (respecting the new .gitignore) and commit
          git add .
          git commit -m "Force clean deployment to Hugging Face"
          
          # Force push this single, clean commit to Hugging Face
          git remote add space https://tokitahmidornob:$HF_TOKEN@huggingface.co/spaces/tokitahmidornob/BioFold-Engine
          git push --force space main
